pipeline:
  name: Build go-pipeline-sample
  identifier: Build_go_pipeline_sample_1705421159607
  projectIdentifier: Shamili_Practice
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: git_integration
        repoName: go-pipeline-sample
        build: <+input>
